name: Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init

      - name: Run Robot Framework tests
        run: robot -d results tests/

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: results/

      - name: Send Email with Results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Robot Framework CI/CD Results
          body: "O CI/CD do Robot Framework foi executado. Segue o relatório em anexo."
          to: marcoseffers@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: |
            results/report.html
            results/log.html
            results/output.xml
